allowBuilds:
  '@swc/core': true
  esbuild: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - unplugin-plugin-userscript@0.3.1
overrides:
  esbuild-plugin-userscript: link:../esbuild-plugin-userscript
  rolldown-plugin-userscript: link:../unplugin-plugin-userscript
  unplugin-plugin-userscript: link:../unplugin-plugin-userscript
