on:
  push:
    paths:
      - '**.ts'
      - '.github/workflows/lint.yaml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9.4.0
          run_install: true
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: 20.x
      - name: Lint
        run: pnpm run lint
