on:
  push:
    tags: ["v*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9.4.0
          run_install: true
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: 20.x
      - name: Build
        run: pnpm build
        env:
          ENVIRONMENT: ci
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: |
            build/index.user.js
            README.md
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: release
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/index.user.js,README.md"
